[package]
name = "enum_offset"
version = "0.1.0"
edition = "2021"
description = "Get offset of fields in enum item using stable Rust"

[lib]
path = "lib.rs"

[dependencies]
enum_offset_macro = { path = "./macro", version = "0.1.0" }

[workspace]
members = [".", "macro"]
resolver = "2"
